# -*- coding: utf-8 -*-
"""Preprocessed_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Fe_3-pRPIZai7Uv7qCDtrO-6ieVeRGa
"""

#1. load data
import pandas as pd
df = pd.read_csv('/content/Dataset_ATS_v2.csv')#load path
df.head()

#we can add a self-defined feature, because tenure implies a potential new user
# which is the length of time a user has been using the service
df = df.copy()
df['IsNewCustomer'] = (df['tenure'] == 0).astype(int)
print(df['IsNewCustomer'].value_counts())

#show the data
df.describe()

# check categorical data with their unique values
categorical_cols = df.select_dtypes(include=['object']).columns
categorical_unique_values = {col: df[col].unique().tolist() for col in categorical_cols}
categorical_unique_values

#see the specific proportion
categorical_value_counts = {
    col: df[col].value_counts().to_dict() for col in categorical_cols
}
categorical_value_counts

#visualise data distribution (categorical)
import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(nrows=4, ncols=2, figsize=(14, 16))
axes = axes.flatten()

for i, col in enumerate(categorical_cols):
    n_colors = df[col].nunique()
    local_palette = sns.color_palette("Set2", n_colors)
    sns.countplot(data=df, x=col, order=df[col].value_counts().index,
                  ax=axes[i], palette=local_palette)
    axes[i].set_title(f"{col} - Value Counts")
    axes[i].set_ylabel("Count")
    axes[i].set_xlabel(col)
    axes[i].tick_params(axis='x', rotation=15)

for j in range(len(categorical_cols), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

#visualise numerical data
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

fig, axes = plt.subplots(nrows=1, ncols=len(numeric_cols), figsize=(18, 5))

for i, col in enumerate(numeric_cols):
    axes[i].hist(df[col], bins=30, color='skyblue', edgecolor='black')
    axes[i].set_title(f"{col} Distribution")
    axes[i].set_xlabel(col)
    axes[i].set_ylabel("Count")

plt.tight_layout()
plt.show()

df

from sklearn.preprocessing import MinMaxScaler

label_column = 'Churn' # y-label
if label_column in df.columns:
    label = df.pop(label_column)
    df[label_column] = label

df[label_column] = df[label_column].map({'Yes': 1, 'No': 0}).astype(int)

# only feature Contract will be processed through one-hot
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
numerical_cols = [col for col in numerical_cols if col != label_column]
categorical_cols = [col for col in categorical_cols if col != label_column]

# other numerical values will be normalized by minmaxscaler
scaler = MinMaxScaler()
df_numerical = pd.DataFrame(scaler.fit_transform(df[numerical_cols]), columns=numerical_cols)

df_contract = pd.get_dummies(df[['Contract']], prefix='Contract')
binary_cats = [col for col in categorical_cols if col != 'Contract']
df_binary = df[binary_cats].apply(lambda x: x.astype('category').cat.codes)

df_processed = pd.concat([df_numerical, df_binary, df_contract, df[label_column]], axis=1)
df_processed.to_csv('/Dataset_processed_for_ANN.csv', index=False)

df_processed

gender_mapping = dict(enumerate(df['gender'].astype('category').cat.categories))
print(gender_mapping)

#heatmap
corr_matrix = df_processed.drop(columns=['Churn']).corr()

plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', square=True, cbar=True)
plt.title('Feature Correlation Heatmap (excluding label)', fontsize=14)
plt.tight_layout()
plt.show()

#corellation betweensfeatures and label

cor_with_label = df_processed.corr()['Churn'].drop('Churn').sort_values(ascending=False)

plt.figure(figsize=(8, 6))
sns.barplot(x=cor_with_label.values, y=cor_with_label.index, palette='crest')
plt.title('Correlation of Features with Churn', fontsize=14)
plt.xlabel('Correlation Coefficient')
plt.tight_layout()
plt.show()

sns.histplot(df_processed['MonthlyCharges'], kde=True)
plt.title("Monthly Charges Distribution")
plt.show()

sns.boxplot(x='Churn', y='MonthlyCharges', data=df_processed)
plt.title("Total Charges Distribution by Churn")
plt.show()

from sklearn.model_selection import train_test_split

X = df_processed.drop('Churn', axis=1)
y = df_processed['Churn']
y = y.astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

train_df = pd.concat([X_train, y_train], axis=1)

test_df = pd.concat([X_test, y_test], axis=1)

train_df.to_csv('train.csv', index=False)
test_df.to_csv('test.csv', index=False)