# -*- coding: utf-8 -*-
"""WIL ACS DATA PREPROCESSING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12N9ENc6ysLjJJCx3HjtK5xuAeUOpJLjC
"""

#1. load data
import pandas as pd
df = pd.read_csv('../data/0_raw/Dataset_ATS_v2.csv')#switch path from colab to git warehouse
#df = pd.read_csv('/content/Dataset_ATS_v2.csv')#load path
df.head()

#we can add a self-defined feature, because tenure implies a potential new user
# which is the length of time a user has been using the service
df = df.copy()
df['IsNewCustomer'] = (df['tenure'] == 0).astype(int)
print(df['IsNewCustomer'].value_counts())

#show the data
df.describe()

# check categorical data with their unique values
categorical_cols = df.select_dtypes(include=['object']).columns
categorical_unique_values = {col: df[col].unique().tolist() for col in categorical_cols}
categorical_unique_values

#see the specific proportion
categorical_value_counts = {
    col: df[col].value_counts().to_dict() for col in categorical_cols
}
categorical_value_counts

#visualise data distribution (categorical)
import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(nrows=4, ncols=2, figsize=(14, 16))
axes = axes.flatten()

for i, col in enumerate(categorical_cols):
    n_colors = df[col].nunique()
    local_palette = sns.color_palette("Set2", n_colors)
    sns.countplot(data=df, x=col, order=df[col].value_counts().index,
                  ax=axes[i], palette=local_palette)
    axes[i].set_title(f"{col} - Value Counts")
    axes[i].set_ylabel("Count")
    axes[i].set_xlabel(col)
    axes[i].tick_params(axis='x', rotation=15)

for j in range(len(categorical_cols), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

#visualise numerical data
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

fig, axes = plt.subplots(nrows=1, ncols=len(numeric_cols), figsize=(18, 5))

for i, col in enumerate(numeric_cols):
    axes[i].hist(df[col], bins=30, color='skyblue', edgecolor='black')
    axes[i].set_title(f"{col} Distribution")
    axes[i].set_xlabel(col)
    axes[i].set_ylabel("Count")

plt.tight_layout()
plt.show()

df



from sklearn.preprocessing import MinMaxScaler

label_column = 'Churn' # y-label
if label_column in df.columns:
    label = df.pop(label_column)
    df[label_column] = label

df[label_column] = df[label_column].map({'Yes': 1, 'No': 0}).astype(int)

# only feature Contract will be processed through one-hot
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
numerical_cols = [col for col in numerical_cols if col != label_column]
categorical_cols = [col for col in categorical_cols if col != label_column]

# other numerical values will be normalized by minmaxscaler
scaler = MinMaxScaler()
df_numerical = pd.DataFrame(scaler.fit_transform(df[numerical_cols]), columns=numerical_cols)

df_contract = pd.get_dummies(df[['Contract']], prefix='Contract')
binary_cats = [col for col in categorical_cols if col != 'Contract']
df_binary = df[binary_cats].apply(lambda x: x.astype('category').cat.codes)

df_processed = pd.concat([df_numerical, df_binary, df_contract, df[label_column]], axis=1)

# add module that no longer creates a file in a fixed directory
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
processed_path = BASE_DIR / 'data' / '2_processed' / 'Dataset_processed_for_ANN.csv'

df_processed.to_csv(processed_path, index=False)

#df_processed.to_csv('/Dataset_processed_for_ANN.csv', index=False) # fixed directory

df_processed

gender_mapping = dict(enumerate(df['gender'].astype('category').cat.categories))
print(gender_mapping)

#heatmap
corr_matrix = df_processed.drop(columns=['Churn']).corr()

plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', square=True, cbar=True)
plt.title('Feature Correlation Heatmap (excluding label)', fontsize=14)
plt.tight_layout()
plt.show()

#corellation betweensfeatures and label

cor_with_label = df_processed.corr()['Churn'].drop('Churn').sort_values(ascending=False)

plt.figure(figsize=(8, 6))
sns.barplot(x=cor_with_label.values, y=cor_with_label.index, palette='crest')
plt.title('Correlation of Features with Churn', fontsize=14)
plt.xlabel('Correlation Coefficient')
plt.tight_layout()
plt.show()

sns.histplot(df_processed['MonthlyCharges'], kde=True)
plt.title("Monthly Charges Distribution")
plt.show()

sns.boxplot(x='Churn', y='MonthlyCharges', data=df_processed)
plt.title("Total Charges Distribution by Churn")
plt.show()

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X_scaled = StandardScaler().fit_transform(df_processed.drop(columns=['Churn']))
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(8,6))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=df_processed['Churn'])
plt.title("PCA Projection (2D)")
plt.show()

from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
import pandas as pd

numeric_df = df_processed.select_dtypes(include=['float64', 'int64'])

X = add_constant(numeric_df)

vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif["features"] = X.columns

print(vif.sort_values("VIF Factor", ascending=False))







#sample ann

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

X = df_processed.drop('Churn', axis=1)
y = df_processed['Churn']
y = y.astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=30, batch_size=32, validation_split=0.2, verbose=0)
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
report = classification_report(y_test, y_pred, output_dict=True)
conf_matrix = confusion_matrix(y_test, y_pred)

# Plot confusion matrix
plt.figure(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=conf_matrix, display_labels=['No Churn', 'Churn'])
disp.plot(cmap=plt.cm.Blues, values_format='d')
plt.title('Confusion Matrix - ANN on Processed Data')
plt.grid(False)
plt.show()

report

